# lists of random data

responses = [
                    "Sorry fella, I don’t have the energy to pretend to like you today.",
                    "Umm...pardon me, I wasn’t listening. Can you repeat what you just said?",
                    "Ok.",
                    "That sounds weird coming from you. Am I? Am I Really?",
                    "Are you always such an idiot, or do you just show off when I’m around?",
                    "Whatever you say, hefe.",
                    "Sorry, I don’t understand what you’re saying. I don’t speak bullsh*t.",
                    "Did it hurt when you fell from heaven? If they ask you why, say: 'Cause it looks like you landed on your face!'",
                    "Awww...are you having a bad day? ",
                    "Thank you very much for thinking about me! Bye.",
                    "*Repeat what they just said back*",
                    "I hope your day is as pleasant as your personality!",
                    "Just so you know, this conversation is being recorded.",
                    "The jerk store called. They said they're all out of...you!",
                    "Your misguided opinion is false but cute.",
                    "Goodbye!",
                    "Cool story bro!",
                    "You know they can hear you, right?",
                    "It is kind of hilarious watching you try to fit your entire vocabulary into one sentence.",
                    "How is that supposed to make me feel?",
                    "There are some incredibly dumb people in this world. Thanks for helping me understand that.",
                    "Look, if I wanted to hear from an asshole, all I had to do was fart.",
                    "I've been called worse things by better people.",
                    "If ignorance is bliss, you must be the happiest person on the planet.", 
                    "You have your entire life to be a jerk. Why not take today off?", 
                    "Please cancel my subscription to your issues.", 
                    "I'm calling the cops.", 
                    "People like you are the reason I’m on medication.", 
                    "I don't care what everyone else says. I don't think you're that bad.", 
                    "May I ask you to stop talking. It smells really bad.", 
                    "Remember when I asked for your opinion? Well, me neither.", 
                    "Thanks for sharing. We’re all refreshed and challenged by your unique point of view.",
                    "Remember that time when I said you were cool? I lied.", 
                    "I have better things to do than listening to you.", 
                    "*Makes sustained eye contact and then licks lips*", 
                    "Your ass must be pretty jealous of all the shit that comes out of your mouth.", 
                    "You always bring me so much joy—as soon as you leave the room.", 
                    "Here’s a tissue, you have some sh*t on your lips.", 
                    "If you ran like your mouth, you’d be in good shape.", 
                    "Mirrors don’t lie, and lucky for you, they also don’t laugh.",
                    "Surprise me. Say something intelligent.", 
                    "Unless your name is Google, stop acting like you know everything.", 
                    "Roses are red; violets are blue. I have five fingers, and the third one is for you.", 
                    "I’d slap you, but that would be animal abuse.", 
                    "Talk to the hand!", 
                    "Wow, you’re really smart!",
                    "I don't have the time nor the crayons to explain it to you."
                ]

girl_names=[

                'Consuelo',
                'Kristi',
                'Tenesha',
                'Sophie',
                'Kacie',
                'Yesenia',
                'Bethanie',
                'Laurinda',
                'Lavina',
                'Ressie',
                'Michael',
                'Eliza',
                'Audrey',
                'Scarlett',
                'Verona',
                'Richelle',
                'Kathe',
                'Latoria',
                'Oretha',
                'Juliana',
                'Christel',
                'Darline',
                'Kristian',
                'Inge',
                'Aide',
                'Linn',
                'George',
                'Dina',
                'Jayna',
                'Lucienne',
                'Kelle',
                'Suzette',
                'Hettie',
                'J Pow',
                'Tamika',
                'Ossie',
                'Analisa',
                'Rosann',
                'Ramona',
                'Arnette',
                'Alesha',
                'Suk',
                'Tricia',
                'Missy',
                'Amber',
                'Kiara',
                'Maida',
                'Marjory',
                'Elsa',
                'Charla',
                'Shawnee',
                'Lili',
                'Jenny',
                'Jonathan'
                ]


blink_songs = [
                    "https://www.youtube.com/watch?v=ioNng23DkIM",
                    "https://www.youtube.com/watch?v=bwmSjveL3Lc",
                    "https://www.youtube.com/watch?v=Amq-qlqbjYA",
                    "https://www.youtube.com/watch?v=IHNzOHi8sJs", 
                    "https://www.youtube.com/watch?v=9pdj4iJD08s", 
                    "https://www.youtube.com/watch?v=dISNgvVpWlo", 
                    "https://www.youtube.com/watch?v=b73BI9eUkjM", 
                    "https://www.youtube.com/watch?v=FzVR_fymZw4"

            ]

baes = [

                    "Lisa", 
                    "Jisoo", 
                    "Rosé", 
                    "Jennie"
        ]


pokemon_text = [
                    ".    _.----.        ____                 ___    ___     ____         .\n",
                    "._.-'       `.     |    |  /`.          |   \  /   |   |    \  |`.   .\n",
                    ".\      __    \    '-.  | /   `.  ___   |    \/    |   '-.   \ |  |  .\n",
                    ". \.    \ \   |  __  |  |/    ,','_  `. |          | __  |    \|  |  .\n",
                    ".  \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |  .\n",
                    ".   \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |  .\n",
                    ".    \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |  .\n",
                    ".     \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |  .\n",
                    ".      \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |  .\n",
                    ".       \_.-'       |__|    `-._ |              '-.|     '-.| |   |  .\n",
                    ".                               `'                            '-._|  .\n"

                ]